# Generated by Django 5.0 on 2023-12-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("admission_date", models.DateField()),
                ("program_of_study", models.CharField(max_length=100)),
                ("student_id", models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
